# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Sentiment Analysis CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: Sentiment_Analysis
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run model training
      working-directory: Sentiment_Analysis/src
      run: |
        python trainer.py
    # - name: Run unit tests
    #   working-directory: Sentiment_Analysis
    #   run: |
    #     pytest test/ 
    

